[keyboard]
bindings = [
{ key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" },
{ key = "Backspace", mods = "Super|Shift", action = "Quit" },
{ key = "E", mods = "Control|Shift", action = "ToggleViMode" }
]
